"""STAGE 1.5: the bake-off runs THROUGH the state machine, and the FORCE lever measurably
changes a weak subject's behavior -- which IS the bake-off signal, produced with no separate
rig and no judge (the engine's terminal state is the objective outcome). Scripted deterministic
subjects prove the plumbing; a real small-model subject is the later dogfood run."""

from __future__ import annotations

import json
import re

from cortex_core.bakeoff import CONDITIONS, make_coding_gate, make_model_subject, run_episode
from cortex_core.llm_parse import extract_tool_call


def test_suggest_and_baseline_carry_different_guidance():
    """The gap that made baseline == l1_suggest is closed: the conditions now emit different
    SEARCH_BRAIN instructions via the engine envelope (not just the same gate)."""
    base = CONDITIONS["baseline"]["chart"]["states"]["SEARCH_BRAIN"]["instruction"]
    sugg = CONDITIONS["l1_suggest"]["chart"]["states"]["SEARCH_BRAIN"]["instruction"]
    assert base != sugg
    assert "search" in sugg.lower() and "may want" in sugg.lower()  # suggests, not requires
    assert "search" not in base.lower()  # baseline doesn't mention it

# A payload that satisfies every phase's permissive default gate (just needs to be a dict);
# `evidence` is what the FORCE gate additionally checks in SEARCH_BRAIN.
_FULL = {"evidence": [{"claim": "c", "source": "s"}], "note": "x", "patch": "x", "verdict": "pass"}
_EMPTY = {"evidence": [], "note": "x", "patch": "x", "verdict": "pass"}


def _lazy_subject(view):
    """Never searches -- submits the phase's advance tool with an EMPTY report every time."""
    return view["legal_tools"][0], _EMPTY  # legal_tools = [advance_tool, *extra_tools]


def _diligent_subject_factory():
    """Searches once in SEARCH_BRAIN, then advances every phase with real evidence."""
    state = {"searched": False}

    def subject(view):
        if view["state"] == "SEARCH_BRAIN" and not state["searched"] and "cortex_search" in view["legal_tools"]:
            state["searched"] = True
            return "cortex_search", {"query": "how X works"}
        return view["legal_tools"][0], _FULL

    return subject


def test_baseline_lets_a_lazy_subject_finish():
    r = run_episode("baseline", {"seeking": "x"}, _lazy_subject)
    assert r["reached_done"] is True
    assert r["searched"] is False  # never had to


def test_force_blocks_a_lazy_subject_at_search():
    r = run_episode("l1_force", {"seeking": "x"}, _lazy_subject)
    assert r["reached_done"] is False
    assert r["outcome"] == "SEARCH_BRAIN"  # forced to search, never did -> stuck


def test_force_lets_a_diligent_subject_finish():
    r = run_episode("l1_force", {"seeking": "x"}, _diligent_subject_factory())
    assert r["reached_done"] is True
    assert r["searched"] is True  # the FORCE lever is what made it search


def test_force_lever_measurably_changes_outcome():
    """The whole thesis in one assert: the SAME lazy subject reaches DONE under baseline but
    not under force. That divergence IS the bake-off signal, generated by running through the
    engine -- objective (terminal state), no judge in the loop."""
    lazy_baseline = run_episode("baseline", {"seeking": "x"}, _lazy_subject)
    lazy_force = run_episode("l1_force", {"seeking": "x"}, _lazy_subject)
    assert lazy_baseline["reached_done"] and not lazy_force["reached_done"]


# --- the model-backed subject (the small-model harness), tested with a fake completer -------

def test_extract_tool_call_picks_outer_object_not_nested_payload():
    # THE bug the dogfood exposed: extract_json_object's "last object" grabbed the inner payload.
    raw = 'let me think...\n{"tool":"cortex_search","payload":{"query":"q"}}'
    obj = extract_tool_call(raw, ["cortex_search", "cortex_report_findings"])
    assert obj["tool"] == "cortex_search"          # not the inner {"query": ...}
    assert obj["payload"]["query"] == "q"


def test_extract_tool_call_prefers_a_legal_tool_and_empties_on_garbage():
    raw = '{"tool":"none","payload":{}} ... {"tool":"cortex_search","payload":{}}'
    assert extract_tool_call(raw, ["cortex_search"])["tool"] == "cortex_search"
    assert extract_tool_call("no json at all here", ["cortex_search"]) == {}


def _canned_reasoning_completer(prompt):
    """Emulates a reasoning model: prose, then a NESTED tool call for the phase's advance tool
    (the exact shape that broke qwen35b's naive parse)."""
    m = re.search(r"ALLOWED TOOLS \(pick exactly ONE\): (\[[^\]]*\])", prompt)
    legal = json.loads(m.group(1).replace("'", '"')) if m else ["cortex_report_findings"]
    tool = legal[0]  # the advance tool
    return (f"I should call {tool} here. Reasoning about the payload...\n"
            f'{{"tool":"{tool}","payload":{{"evidence":[{{"claim":"c","source":"s"}}],"result":"done"}}}}')


def test_model_subject_with_nested_json_reaches_done_with_no_coerces():
    log = []
    r = run_episode("baseline", {"seeking": "x"}, make_model_subject(_canned_reasoning_completer, log=log))
    assert r["reached_done"] is True
    assert not any(e[0] == "COERCE" for e in log)  # nested JSON parsed cleanly -> the model drove it


def test_garbage_model_gets_stuck_under_force_not_carried():
    """Measurement integrity: a model that never emits a valid tool call must get STUCK under
    force (the honest fallback uses an EMPTY payload, so the force gate blocks it) -- NOT be
    silently carried to DONE by the harness fabricating evidence."""
    r = run_episode("l1_force", {"seeking": "x"}, make_model_subject(lambda p: "I refuse to output JSON."))
    assert r["reached_done"] is False
    assert r["outcome"] == "SEARCH_BRAIN"


# --- GAP-0022: a deterministic checker gate makes the bake-off measure real CORRECTNESS -----

def _add_checker(patch):
    """Deterministic checker for 'implement add(a,b)': run the submitted code, verify behavior.
    No judge -- pure execution."""
    ns: dict = {}
    try:
        exec(patch, ns)  # controlled: the patch is scripted in these tests
    except Exception as exc:  # noqa: BLE001
        return False, f"did not compile: {exc}"
    add = ns.get("add")
    if not callable(add):
        return False, "no add() defined"
    try:
        ok = add(2, 3) == 5 and add(-1, 1) == 0 and add(0, 0) == 0
    except Exception as exc:  # noqa: BLE001
        return False, f"add() raised: {exc}"
    return ok, "checked add(2,3), add(-1,1), add(0,0)"


def _submitter(patch_src):
    def subject(view):
        return view["legal_tools"][0], {"evidence": [{"claim": "c", "source": "s"}],
                                        "patch": patch_src, "result": "done"}
    return subject


def test_coding_gate_passes_correct_code_and_reaches_done():
    gate = make_coding_gate(_add_checker)
    r = run_episode("baseline", {"seeking": "implement add"},
                    _submitter("def add(a, b):\n    return a + b\n"), gate=gate)
    assert r["reached_done"] is True  # deterministic checker confirmed correctness


def test_coding_gate_fails_wrong_code_and_blocks_done():
    """The whole point of GAP-0022: WRONG code cannot reach DONE, because a real checker (not a
    judge) gates the coding phases. It reworks/escalates and terminates without a clean pass."""
    gate = make_coding_gate(_add_checker)
    r = run_episode("baseline", {"seeking": "implement add"},
                    _submitter("def add(a, b):\n    return a - b\n"), gate=gate)  # subtracts!
    assert r["reached_done"] is False  # objectively wrong -> the checker blocks it


_ADD_BAKEOFF_TASK = {
    "title": "add", "entry": "add",
    "cases": [{"args": [2, 3], "expected": 5}], "hidden": [{"args": [-1, 1], "expected": 0}],
    "reference": "def add(a, b):\n    return a + b\n", "prompt": "Define add(a,b) -> a+b.",
}


def test_coding_subject_solves_real_task_end_to_end():
    """The full real-bake-off loop (the milestone): a subject SOLVES the task at IMPLEMENT and a
    deterministic checker (incl. hidden) confirms -- no judge. Correct code -> DONE; wrong -> not."""
    from cortex_core.bakeoff import make_coding_subject
    from cortex_core.bakeoff_tasks import build_checker

    gate = make_coding_gate(build_checker(_ADD_BAKEOFF_TASK))
    good = make_coding_subject(lambda p: "def add(a, b):\n    return a + b\n", _ADD_BAKEOFF_TASK)
    assert run_episode("baseline", {"seeking": "add"}, good, gate=gate)["reached_done"] is True

    bad = make_coding_subject(lambda p: "def add(a, b):\n    return a * b\n", _ADD_BAKEOFF_TASK)
    assert run_episode("baseline", {"seeking": "add"}, bad, gate=gate)["reached_done"] is False
